# Site settings
title: "docassemble-openlcbr"
email: "jason@roundtablelaw.ca"
description: >-
  A package to extend open-source expert system tool docassemble to be able to use analogical case based reasoning from openlcbr.
baseurl: ""
url: "https://Gauntlet173.github.io/docassemble-openlcbr"
repository: Gauntlet173/docassemble-openlcbr
github_username: Gauntlet173
collections:
  docs:
    output: true
defaults:
  - scope:
      path: "docs"
      type: docs
    values:
      layout: docs

# Build settings
markdown: kramdown
exclude:
  - .git
  - subdocs
  - CHANGELOG.yml
